### ISSUE TITLE
SEO: Complete Open Graph and Meta Data Implementation

### ISSUE THREAD

**Issue by TedTschopp** [TedTschopp/tedt.org#21]
## Issue Description
Complete the implementation of Open Graph meta data and other missing SEO metadata that is currently marked as TODO in the `_includes/meta-data-seo.html` file.

## Current State
The meta-data-seo.html file contains several TODO comments indicating incomplete metadata implementation:

```html
<!-- TODO: Add all this in and wire it up -->
<meta property="og:article:published_time" content="..">
```

### 1. Open Graph Article Metadata
Currently missing essential article-specific Open Graph tags:

```html
<!-- Article-specific Open Graph tags to implement -->
<meta property="og:article:published_time" content="{{ page.date | date_to_xmlschema }}">
<meta property="og:article:modified_time" content="{{ page.last_modified_at | default: page.date | date_to_xmlschema }}">
<meta property="og:article:author" content="{{ page.author | default: site.author.name }}">
<meta property="og:article:section" content="{{ page.categories | first }}">
<meta property="og:article:tag" content="{{ page.tags | join: ',' }}">
<meta property="og:article:expiration_time" content="{{ page.expires_at | date_to_xmlschema }}">
```

### 2. Twitter Card Enhanced Metadata
Missing advanced Twitter Card features:

```html
<!-- Enhanced Twitter Card metadata -->
<meta name="twitter:label1" content="Reading time">
<meta name="twitter:data1" content="{{ page.reading_time | default: '5' }} min read">
<meta name="twitter:label2" content="Published">
<meta name="twitter:data2" content="{{ page.date | date: '%B %d, %Y' }}">
```

### 3. JSON-LD Structured Data
Missing structured data for better search engine understanding:

```html
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "{{ page.title | escape }}",
  "author": {
    "@type": "Person",
    "name": "{{ page.author | default: site.author.name }}"
  },
  "datePublished": "{{ page.date | date_to_xmlschema }}",
  "dateModified": "{{ page.last_modified_at | default: page.date | date_to_xmlschema }}",
  "description": "{{ page.excerpt | strip_html | truncate: 160 | escape }}",
  "image": "{{ page.image | default: site.default_image | absolute_url }}",
  "url": "{{ page.url | absolute_url }}"
}
</script>
```

### 4. Additional SEO Meta Tags
Missing meta tags for enhanced SEO:

```html
<!-- Additional SEO metadata -->
<meta name="robots" content="{{ page.robots | default: 'index,follow' }}">
<meta name="googlebot" content="{{ page.googlebot | default: 'index,follow' }}">
<meta name="bingbot" content="{{ page.bingbot | default: 'index,follow' }}">
<meta name="theme-color" content="{{ site.theme_color | default: '#222222' }}">
<meta name="msapplication-TileColor" content="{{ site.tile_color | default: '#222222' }}">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

### Phase 1: Open Graph Article Tags
```liquid
<!-- _includes/open-graph-article.html -->
{% if page.layout == 'post' %}
  <meta property="og:type" content="article">
  <meta property="og:article:published_time" content="{{ page.date | date_to_xmlschema }}">
  {% if page.last_modified_at %}
    <meta property="og:article:modified_time" content="{{ page.last_modified_at | date_to_xmlschema }}">
  {% endif %}
  {% if page.author %}
    <meta property="og:article:author" content="{{ page.author }}">
  {% endif %}
  {% if page.categories %}
    {% for category in page.categories %}
      <meta property="og:article:section" content="{{ category }}">
    {% endfor %}
  {% endif %}
  {% if page.tags %}
    {% for tag in page.tags %}
      <meta property="og:article:tag" content="{{ tag }}">
    {% endfor %}
  {% endif %}
{% else %}
  <meta property="og:type" content="website">
{% endif %}
```

### Phase 2: Enhanced Twitter Cards
```liquid
<!-- _includes/twitter-card-enhanced.html -->
<meta name="twitter:card" content="{{ page.twitter_card | default: 'summary_large_image' }}">
<meta name="twitter:site" content="@{{ site.twitter_username }}">
<meta name="twitter:creator" content="@{{ page.author_twitter | default: site.twitter_username }}">
<meta name="twitter:title" content="{{ page.title | default: site.title | escape }}">
<meta name="twitter:description" content="{{ page.excerpt | default: site.description | strip_html | truncate: 200 | escape }}">
<meta name="twitter:image" content="{{ page.image | default: site.default_social_image | absolute_url }}">

{% if page.layout == 'post' %}
  <meta name="twitter:label1" content="Reading time">
  <meta name="twitter:data1" content="{% if page.reading_time %}{{ page.reading_time }}{% else %}{{ content | number_of_words | divided_by: 200 | plus: 1 }}{% endif %} min read">
  <meta name="twitter:label2" content="Published">
  <meta name="twitter:data2" content="{{ page.date | date: '%B %d, %Y' }}">
{% endif %}
```

### Phase 3: JSON-LD Structured Data
```liquid
<!-- _includes/json-ld-article.html -->
{% if page.layout == 'post' %}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": "{{ page.title | escape }}",
  "description": "{{ page.excerpt | default: site.description | strip_html | truncate: 160 | escape }}",
  "image": {
    "@type": "ImageObject",
    "url": "{{ page.image | default: site.default_social_image | absolute_url }}",
    "width": 1200,
    "height": 630
  },
  "author": {
    "@type": "Person",
    "name": "{{ page.author | default: site.author.name }}",
    "url": "{{ site.url }}"
  },
  "publisher": {
    "@type": "Organization",
    "name": "{{ site.title }}",
    "logo": {
      "@type": "ImageObject",
      "url": "{{ site.logo | absolute_url }}",
      "width": 200,
      "height": 60
    }
  },
  "datePublished": "{{ page.date | date_to_xmlschema }}",
  "dateModified": "{{ page.last_modified_at | default: page.date | date_to_xmlschema }}",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "{{ page.url | absolute_url }}"
  },
  "url": "{{ page.url | absolute_url }}",
  "wordCount": {{ content | number_of_words }},
  "keywords": [
    {% for tag in page.tags %}
      "{{ tag }}"{% unless forloop.last %},{% endunless %}
    {% endfor %}
  ],
  "articleSection": "{{ page.categories | first }}",
  "inLanguage": "en-US"
}
</script>
{% endif %}
```

### Phase 4: Update Main Meta Include
```liquid
<!-- Update _includes/meta-data-seo.html -->
{% include open-graph-article.html %}
{% include twitter-card-enhanced.html %}
{% include json-ld-article.html %}

<!-- Additional SEO meta tags -->
<meta name="robots" content="{{ page.robots | default: 'index,follow' }}">
<meta name="theme-color" content="{{ site.theme_color | default: '#222222' }}">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

### _config.yml Additions
```yaml
# SEO Configuration
author:
  name: "Ted Tschopp"
  twitter: "tedtschopp"

seo:
  default_social_image: "/img/default-social.jpg"
  theme_color: "#222222"
  tile_color: "#222222"

# Twitter Configuration
twitter_username: "tedtschopp"

# Logo for structured data
logo: "/img/logo.png"
```

### SEO Testing Tools
1. **Open Graph Debugger**: https://developers.facebook.com/tools/debug/
2. **Twitter Card Validator**: https://cards-dev.twitter.com/validator
3. **Google Rich Results Test**: https://search.google.com/test/rich-results
4. **Structured Data Testing Tool**: https://validator.schema.org/

### Validation Checklist
- [ ] Open Graph tags validate without errors
- [ ] Twitter Cards display correctly in validator
- [ ] JSON-LD passes Google Rich Results test
- [ ] All meta tags render with proper content
- [ ] No duplicate or conflicting meta tags
- [ ] Mobile-specific meta tags function correctly

## Expected Benefits
- **Improved Social Sharing**: Rich previews on social media platforms
- **Enhanced Search Results**: Rich snippets in Google search
- **Better Analytics**: More detailed social media tracking
- **Professional Appearance**: Consistent branding across platforms

## Files to Modify
- `_includes/meta-data-seo.html` (main update)
- `_includes/open-graph-article.html` (new)
- `_includes/twitter-card-enhanced.html` (new)
- `_includes/json-ld-article.html` (new)
- `_config.yml` (configuration additions)

## Success Metrics
- Open Graph Debugger shows no errors
- Twitter Card Validator displays rich cards
- Google Rich Results test passes
- Social media shares show rich previews
- Search results include rich snippets

## Priority
**High** - Essential for proper SEO and social media integration

## Related Issues
- Issue #72: Schema.org structured data (complementary implementation)
- Issue #46: Site scanning for SEO validation

**Comment by TedTschopp** [comment]
Progress Note: Partial implementation completed.

Already Implemented in `_includes/seo/meta-data-seo.html`:
- Core OG tags (title, description, type switching between website/article, image, site_name, url, locale)
- Article meta: `article:published_time`, `article:modified_time` (when update), `article:section`, `article:tag` loop (limited to 12)
- Twitter Card metadata including dynamic large vs summary, title, description, image alt
- JSON-LD: WebSite + Article graph with headline, description, image, datePublished/Modified, keywords, articleSection, breadcrumb (single category), mainEntityOfPage

Still Missing From Original Acceptance Criteria / Description Examples:
- Enhanced Twitter labels (reading time, published date meta pairs) not yet present
- Multiple author support (still single author placeholders, TODO comment remains)
- Additional meta (robots variants, theme-color, etc.) partially elsewhere but not fully consolidated per plan
- Structured data could include publisher Organization/logo and wordCount for richer snippets

Recommendation:
- Keep issue open and adjust checklist to remaining gaps: multi-author metadata, twitter label/data pairs, publisher org, wordCount, theme-color centralization.
- Optionally spin off multiple author implementation to Issue #15 to avoid scope creep here.

Next Step Suggestion: Update issue body with a "Completed" vs "Remaining" section for clarity.
